export const FETCH_CONVERSATIONS_REQUEST = "FETCH_CONVERSATIONS_REQUEST";
export const FETCH_CONVERSATIONS_SUCCESS = "FETCH_CONVERSATIONS_SUCCESS";
export const FETCH_CONVERSATIONS_FAILURE = "FETCH_CONVERSATIONS_FAILURE";

export const FETCH_MESSAGES_REQUEST = "FETCH_RANDOM_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_RANDOM_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_RANDOM_MESSAGES_FAILURE";

export const ADD_CONVERSATION_REQUEST = "ADD_CONVERSATION_REQUEST";
export const ADD_CONVERSATION_SUCCESS = "ADD_CONVERSATION_SUCCESS";
export const ADD_CONVERSATION_FAILURE = "ADD_CONVERSATION_FAILURE";

export const DELETE_CONVERSATION_REQUEST = "DELETE_CONVERSATION_REQUEST";
export const DELETE_CONVERSATION_SUCCESS = "DELETE_CONVERSATION_SUCCESS";
export const DELETE_CONVERSATION_FAILURE = "DELETE_CONVERSATION_FAILURE";


export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILURE = "DELETE_MESSAGE_FAILURE";

export const ARRIVING_MESSAGE_UPDATE = "ARRIVING_MESSAGE_UPDATE";
export const RESET_MESSAGE_REDUCER = "RESET_MESSAGE_REDUCER_UPDATE";