// profileActionTypes.js
export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILED  = "SEARCH_USER_FAILED";
export const REMOVE_SEARCH_USER  = "REMOVE_SEARCH_USER";

export const RESET_SEARCH_REDUCER = "RESET_SEARCH_REDUCER";