// actionTypes.js
export const UPDATE_SELECTED_CONVERSATION_ID =
  "UPDATE_SELECTED_CONVERSATION_ID";
export const UPDATE_PROFILE_STATES = "UPDATE_PROFILE_STATES";
export const UPDATE_RECEIVER_ID = "UPDATE_RECEIVER_ID";
export const UPDATE_RECEIVER_PROFILE = "UPDATE_RECEIVER_PROFILE";
export const UPDATE_SOCKET = "UPDATE_SOCKET";
export const UPDATE_SOCKET_CONNECTION = "UPDATE_SOCKET_CONNECTION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const UPDATE_BLOCKED_ACCOUNT = "UPDATE_BLOCKED_ACCOUNT";
export const UPDATE_ISTYPING = "UPDATE_ISTYPING";
