// profileActionTypes.js

export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const BLOCK_ACCOUNT_REQUEST = "BLOCK_ACCOUNT_REQUEST";
export const BLOCK_ACCOUNT_SUCCESS = "BLOCK_ACCOUNT_SUCCESS";
export const BLOCK_ACCOUNT_FAILURE = "BLOCK_ACCOUNT_FAILURE";

export const UNBLOCK_ACCOUNT_REQUEST = "UNBLOCK_ACCOUNT_REQUEST";
export const UNBLOCK_ACCOUNT_SUCCESS = "UNBLOCK_ACCOUNT_SUCCESS";
export const UNBLOCK_ACCOUNT_FAILURE = "UNBLOCK_ACCOUNT_FAILURE";

export const ADD_NOTIFICATION_REQUEST = "ADD_NOTIFICATION_REQUEST";
export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS";
export const ADD_NOTIFICATION_FAILURE = "ADD_NOTIFICATION_FAILURE";

export const REMOVE_NOTIFICATION_REQUEST = "REMOVE_NOTIFICATION_REQUEST";
export const REMOVE_NOTIFICATION_SUCCESS = "REMOVE_NOTIFICATION_SUCCESS";
export const REMOVE_NOTIFICATION_FAILURE = "REMOVE_NOTIFICATION_FAILURE";

export const FETCH_NOTIFICATION_REQUEST = "FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILURE = "FETCH_NOTIFICATION_FAILURE";

export const RESET_PROFILE_REDUCER = "RESET_PROFILE_REDUCER";
